runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v1
  with:
    java-version: '8'
    java-package: jdk
    architecture: x64
- run: |
  find -name "*.java" -not -path "*/test/*" > sources.txt
  javac @sources.txt -d out
  jar --create --file CarlsenBot.jar --manifest ./src/META-INF/MANIFEST.MF -C out/ .
  java -jar CarlsenBot.jar